image: maven:3.9-eclipse-temurin-17

stages:
  - build
  - test
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B"

cache:
  key: maven
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - cd TourGuide
    - mvn $MAVEN_CLI_OPTS -DskipTests=true clean compile

unit_tests:
  stage: test
  script:
    - cd TourGuide
    - mvn $MAVEN_CLI_OPTS test

package_jar:
  stage: package
  script:
    - cd TourGuide
    - mvn $MAVEN_CLI_OPTS -DskipTests=true package
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - TourGuide/target/*.jar
